# Generated by Django 3.2 on 2021-05-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(default='up_', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('inputfile', models.FileField(upload_to='user/inputfile/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/product/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.published')),
                ('typefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.typefile')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
