# Generated by Django 3.2 on 2021-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210509_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
