# Generated by Django 3.2 on 2021-05-12 05:05

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_alter_uploadfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='inputfile',
            field=models.FileField(blank=True, null=True, upload_to='user/inputfile/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('user',)),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
