# Generated by Django 3.2 on 2021-05-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'หมวดหมู่', 'verbose_name_plural': 'ข้อมูลหมวดหมู่'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'สินค้า', 'verbose_name_plural': 'ข้อมูลสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='published',
            options={'ordering': ('name',), 'verbose_name': 'การเผยแพร่', 'verbose_name_plural': 'ข้อมูลการเผยแพร่'},
        ),
        migrations.AlterModelOptions(
            name='typefile',
            options={'ordering': ('name',), 'verbose_name': 'รูปแบบ', 'verbose_name_plural': 'ข้อมูลรูปแบบ'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
