# Generated by Django 3.2 on 2021-05-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210505_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('inputfile', models.FileField(upload_to='user/inputfile/')),
                ('image', models.ImageField(upload_to='user/product/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.published')),
                ('typefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.typefile')),
            ],
        ),
    ]
